In [1]:
import pandas as pd
import sqlite3

# 1. Conectando ao banco de dados da Sprint 1 (voltamos uma pasta com ../)
conexao = sqlite3.connect('../data/processed/ecommerce.db')

# 2. Puxando a tabela inteira usando uma consulta SQL básica
df_vendas = pd.read_sql_query("SELECT * FROM vendas", conexao)

# 3. Exibindo as 5 primeiras linhas para garantir que os dados vieram certinhos
display(df_vendas.head())

,ID_Transacao,Data_Venda,ID_Cliente,Nome_Produto,Categoria_Produto,Valor_Unitario,Quantidade,Valor_Total
0,TRX00001,2025-09-30 00:00:00,CUST419,Vinil de Blues Clássico,Música,210.0,4,840.0
1,TRX00002,2025-08-06 00:00:00,CUST083,Moletom BTS Tour,Vestuário,150.0,4,600.0
2,TRX00003,2025-09-14 00:00:00,CUST420,Livro Ordem Paranormal: Hextombe,Livros,75.0,1,75.0
3,TRX00004,2025-08-28 00:00:00,CUST331,Panetone Trufado de Chocolate,Alimentos,85.9,2,171.8
4,TRX00005,2025-03-21 00:00:00,CUST204,Vinil de Blues Clássico,Música,210.0,2,420.0

In [2]:
# PERGUNTA 1: Qual o faturamento total da loja?
faturamento = df_vendas['Valor_Total'].sum()
print(f"Faturamento Total da Loja: R$ {faturamento:,.2f}\n")

# PERGUNTA 2: Quais são os 3 produtos mais vendidos (em quantidade)?
produtos_top3 = df_vendas.groupby('Nome_Produto')['Quantidade'].sum().sort_values(ascending=False).head(3)
print("--- TOP 3 Produtos Mais Vendidos ---")
print(produtos_top3, "\n")

# PERGUNTA 3: Qual categoria traz mais receita? (Resolvendo com SQL avançado)
query_categorias = """
    SELECT Categoria_Produto, SUM(Valor_Total) as Receita_Total
    FROM vendas
    GROUP BY Categoria_Produto
    ORDER BY Receita_Total DESC
"""
df_categorias = pd.read_sql_query(query_categorias, conexao)

print("--- Receita por Categoria (Consulta SQL) ---")
display(df_categorias)

# Fechando a conexão com o banco por segurança
conexao.close()

Faturamento Total da Loja: R$ 1,484,579.60

--- TOP 3 Produtos Mais Vendidos ---
Nome_Produto
Box Anne with an E (DVD)            1555
Moletom BTS Tour                    1512
Livro Ordem Paranormal: Hextombe    1488
Name: Quantidade, dtype: int64

--- Receita por Categoria (Consulta SQL) ---

  Categoria_Produto  Receita_Total
0            Música       558570.0
1         Vestuário       311460.0
2        Brinquedos       171953.5
3    Entretenimento       155344.5
4         Alimentos       113731.6
5            Livros       111600.0
6  Acessórios Gamer        61920.0